create table categories (
    id int4 generated by default as identity primary key,
    name text not null
);

create table items (
    id int4 generated by default as identity primary key,
    sku text,
    name text not null,
    description text,
    price numeric(10,2) not null,
    quantity int4 not null default 0,
    category_id int4 references categories(id)
);

create table orders (
    id int4 generated by default as identity primary key,
    customer_id int4 not null,
    item_id int4 references items(id),
    quantity int4 not null,
    order_date date,
    status text not null
);

insert into categories (name) values
('Electronics'),
('Furniture');

insert into items (sku, name, description, price, quantity, category_id) values
('I1', 'MacBook Pro', 'Laptop', 1999.99, 5, 1),
('I2', 'iPhone 15', 'Smartphone', 999.99, 8, 1),
('I3', 'Gaming Chair', 'Chair', 249.99, 3, 2),
('I4', 'PS5', 'Console', 499.99, 2, 1),
('I5', 'iPad', 'Tablet', 699.99, 4, 1);

insert into orders (customer_id, item_id, quantity, order_date, status) values
(1, 1, 2, '2026-04-20', 'pending'),
(2, 2, 1, '2026-04-20', 'dispatched'),
(3, 3, 4, '2026-04-21', 'completed'),
(4, 4, 1, '2026-04-22', 'processing'),
(5, 5, 2, '2026-04-23', 'cancelled');